### ISSUE TITLE
Fishy issues

### ISSUE THREAD

**Issue by flashfish0x** [yearn/yearn-vaults-v3#138]
1. Revoke doesn't change totalDebt. Any debt in revoked strategies remains on the balance sheet.

https://github.com/jmonteer/yearn-vaults-v3/blob/84c7bac21fe0b26542282019133d5fc69f3aed46/contracts/VaultV3.vy#L601

2. Migrate and tend break ERC4626
https://github.com/jmonteer/yearn-vaults-v3/blob/84c7bac21fe0b26542282019133d5fc69f3aed46/contracts/VaultV3.vy#L18
https://github.com/jmonteer/yearn-vaults-v3/blob/84c7bac21fe0b26542282019133d5fc69f3aed46/contracts/VaultV3.vy#L616

**Comment by flashfish0x** [comment]
> 1. a revoked strategy needs to be with debt = 0 so there's no need to change total debt
> 2. migrate_strategy can skip migrate call in strategy by setting the second argument to False
>    tend_strategy should not be called on ERC4626 protocols (tend is optional when operating a strategy). maybe it is good to add an extra check so we don't get reverts under any circumstance

how do you remove a strategy that is misbehaving?

**Comment by flashfish0x** [comment]
> you need to migrate

that's not good enough. Assume that a strategy is misbehaving and can no longer be trusted. there needs to be a way to remove it without asking for the strategies permission

**Comment by flashfish0x** [comment]
w/r to point two, why did you decide to include tend in the vault contract?

**Comment by Schlagonia** [comment]
Fixed https://github.com/yearn/yearn-vaults-v3/commit/8f1abb2dfb5d3f71cdb561049d5cb68644eff1ba
