### ISSUE TITLE
Should we express the `maxDebt` in percentage instead of token amount?

### ISSUE THREAD

**Issue by pandadefi** [yearn/yearn-vaults-v3#49]
Unlike v2 we are expressing the number of tokens a strategy can borrow in a number of tokens.
This is not a great approach since the amount of debt a vault will old will greatly change.
A strategy could be allowed to borrow 100% of the funds in the vault after a vault total assets significantly decreased. Or some funds could be left not managed if the total asset in the vault significantly increased.

We should reintroduce a ratio mechanism in percentage. See:
https://github.com/yearn/yearn-vaults/blob/main/contracts/Vault.vy#L85

**Comment by jmonteer** [comment]
I am split between the two approaches. 

On the one hand, using token amount is in line with the way the security team and vault management do the debt allocation. They currently say: "I want to allocate a maximum amount of 5m DAI to this strategy, what is the equivalent debt ratio?" and they set the new debt ratio. Then in following harvests they keep that amount (and change debtRatio accordingly). 

It also helps with APR management. A strategy can take extra 5m but doesn't understand debt ratios (%). Therefore, vault managers just calculate the amount in tokens then do the reverse calc to get the debt ratio. 

On the other hand, I agree % debt ratios are better for those vaults that change a lot in TVL to be kept rebalanced. However, I think this can be achieved by a layer on top (debt allocator). Let's say that maxDebts are refreshed regularly, then the Debt Allocator will do the calcs to get maxDebt and push that number. 

My opinion is currently leaning towards using number of tokens. Any functionality provided by debt ratios as % can still be implemented by the Debt Allocator. 

I confirmed this understanding with the Vault management team just in case.

**Comment by jmonteer** [comment]
We decided to go with fixed amounts of tokens. We will revisit this in the future.
