### ISSUE TITLE
Should _update_debt take the target debt as an argument? 

### ISSUE THREAD

**Issue by jmonteer** [yearn/yearn-vaults-v3#73]
Right now, `update_debt` function will make the `current_debt` of the strategy to the `max_debt` specified by the DEBT_ALLOCATOR role.

This means that the vault will effectively be using `max_debt` as `target_debt`. 

To avoid storing the `target_debt` every time we change it, I think we should consider allowing an input for the DEBT_ALLOCATOR role to fill target debt.
Result: 
`def _update_debt(strategy: address, target_debt: address)`

Target debt would be capped to `max_debt` in any case (as stored in the strategy params). 

This allows to put a limit on the debt as guardrails but also use interesting ways to calculate debt allocation on/off-chain that does not require saving it, at let the DEBT_ALLOCATOR decide (in a way that can be implemented in the future).

**Comment by storming0x** [comment]
I like this idea, i think an argument makes it flexible to things we cant think about at the moment for the upstream modules to use
