### ISSUE TITLE
Add (optional) whitelisting module

### ISSUE THREAD

**Issue by jmonteer** [yearn/yearn-vaults-v3#79]
**Description:** 
Background: 
#74 

During initialisation, the instance deployer should have the possibility to specify a smart contract address where the vault will check for whitelisting. 

This allows instance deployer to release their own guest selection mechanism (e.g. veYFI holders, cryptopunk holders, ...) 

This would include a immutable variable that holds that address. If the address is set to 0 at initialization, the deposits will be open for anyone. 

The variable is immutable because it will save a lot of gas and makes impossible to enable censorship once instantiated permissionless. 

Withdraws will never be permissioned in any case. 

**Dependencies:**
NA

**Acceptance criteria:** 
- code in VaultV3.vy
- tests

**Payment Trigger:** 
PR is merged
**Category:**
DEV
**Level:**
1

**Comment by bufander** [comment]
I've pushed a first draft of how it could look like -> PR: https://github.com/jmonteer/yearn-vaults-v3/pull/90

We can discuss it form here. If favorable I can add more test to our test suite.

**Comment by banteg** [comment]
even if the described examples are fine, i think this feature can potentially be abused and it's better not to have it in the first place

**Comment by storming0x** [comment]
https://github.com/jmonteer/yearn-vaults-v3/pull/90#discussion_r967168005
checked the PR, left some comments, if we feel we must do it, maybe making the language vague and extracting from core as factory like J said, but still leaning towards a philosophical "nope" we shouldnt add it
