### ISSUE TITLE
Add parameterised tests for different ERC20 flavors

### ISSUE THREAD

**Issue by jmonteer** [yearn/yearn-vaults-v3#95]
**Description:** 
Tests should be parameterised with different tokens. 

examples: 
USDT has special cases around not complying exactly with ERC20
USDC 6 decimals
WBTC 8 decimals
some other with 2 decimals

vault should be 100% compatible with at least: 
USDC, USDT, DAI, WBTC, WETH and YFI

**Dependencies:**
NA

**Acceptance criteria:** 
- tests running for different flavors of ERC20 tokens

**Payment Trigger:** 
PR is merged
**Category:**
DEV
**Level:**
2

**Comment by bufander** [comment]
I've given some research. Used `xdist` and run tests with `ape test -n auto`. Unfortunately it doesn't work. 

any idea from you guys?
